# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

create_binmm <- function(file, binfile, type = "double", skip = 0L, header = TRUE, sep = ',', verbose = FALSE) {
    .Call('_sdr_create_binmm', PACKAGE = 'sdr', file, binfile, type, skip, header, sep, verbose)
}

meta_binmm <- function(file, verbose = FALSE) {
    .Call('_sdr_meta_binmm', PACKAGE = 'sdr', file, verbose)
}

subset_binmm <- function(file, ii, jj, standardize = FALSE, verbose = FALSE) {
    .Call('_sdr_subset_binmm', PACKAGE = 'sdr', file, ii, jj, standardize, verbose)
}

