# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

retoMat <- function(file, skip = 0L, header = TRUE, sep = ',', verbose = TRUE) {
    .Call('_sdr_retoMat', PACKAGE = 'sdr', file, skip, header, sep, verbose)
}

retoMat_subset <- function(x, i, j, standardize = FALSE, sep = ',', verbose = FALSE) {
    .Call('_sdr_retoMat_subset', PACKAGE = 'sdr', x, i, j, standardize, sep, verbose)
}

